# Generated by Django 5.0.6 on 2024-06-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_slug_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Отчество'),
        ),
    ]
